tasks:
  path: /
  controller: App\Controller\TaskController::list

task.create:
  path: /create
  controller: App\Controller\TaskController::create

task.create.from.need:
  path: /create/need/{needId}
  controller: App\Controller\TaskController::create

task.edit:
  path: /{taskId}/edit
  controller: App\Controller\TaskController::edit

task.detail:
  path: /{taskId}
  controller: App\Controller\TaskController::detail

task.update_status:
    path: /{taskId}/update_status
    controller: App\Controller\TaskController::updateStatus

