things:
  path: /
  controller: App\Controller\ThingController::list

things.create:
  path: /create
  controller: App\Controller\ThingController::create

things.edit:
  path: /{thingId}/edit
  controller: App\Controller\ThingController::update

things.delete:
  path: /{thingId}/delete
  controller: App\Controller\ThingController::delete

things.detail:
    path: /{thingId}/
    controller: App\Controller\ThingController::detail


