#index:
#    path: /
#    controller: App\Controller\DefaultController::index

login:
  path: /login
  controller: App\Controller\SecurityController::login

logout:
  path: /logout
  controller: App\Controller\SecurityController::logout

home:
  path: /
  controller: App\Controller\HomeController::home

admin:
  path: /admin
  controller: App\Controller\HomeController::admin

places:
  resource: "./routes/places.yaml"
  prefix: /places

things:
  resource: "./routes/things.yaml"
  prefix: /things

tasks:
  resource: "./routes/tasks.yaml"
  prefix: /tasks
