login:
  path: /login
  controller: App\Controller\SecurityController::login

registration:
  path: /registration
  controller: App\Controller\SecurityController::register

logout:
  path: /logout
  controller: App\Controller\SecurityController::logout

users.admin:
  path: /admin/users
  controller: App\Controller\UserController::adminUsers

users.admin.create:
  path: /admin/users/create
  controller: App\Controller\UserController::adminUsersCreate

users.admin.edit:
  path: /admin/users/{userId}/edit
  controller: App\Controller\UserController::adminUsersEdit

users.admin.detail:
  path: /admin/users/{userId}
  controller: App\Controller\UserController::adminUsersDetail

users.profile:
  path: /profile
  controller: App\Controller\UserController::profile

users.profile.edit:
  path: /profile/edit
  controller: App\Controller\UserController::profileEdit

users.profile.edit_password:
    path: /profile/edit/password
    controller: App\Controller\UserController::editPassword

home:
  path: /
  controller: App\Controller\DashboardController::index

places:
  resource: "./routes/places.yaml"
  prefix: /places

things:
  resource: "./routes/things.yaml"
  prefix: /things

tasks:
  resource: "./routes/tasks.yaml"
  prefix: /tasks
