#index:
#    path: /
#    controller: App\Controller\DefaultController::index

login:
  path: /
  controller: App\Controller\SecurityController::login

logout:
  path: /logout
  controller: App\Controller\SecurityController::logout

home:
  path: /home
  controller: App\Controller\HomeController::home

