login:
  path: /login
  controller: App\Controller\SecurityController::login

logout:
  path: /logout
  controller: App\Controller\SecurityController::logout

home:
  path: /
  controller: App\Controller\TaskController::list

places:
  resource: "./routes/places.yaml"
  prefix: /places

things:
  resource: "./routes/things.yaml"
  prefix: /things

tasks:
  resource: "./routes/tasks.yaml"
  prefix: /tasks
